version: '3.8'

services:
  back-end:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back-end/src:/app/back-end/src
      - ./back-end/requirements.txt:/app/back-end/requirements.txt

  front-end:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    ports:
      - "3000:3000"